language: java
jdk:
  - oraclejdk7
notifications:
  email:  
     recipients:
       -  y_jiajun_16@hotmail.com
       -  sgandolfo@fi.uba.ar
       -  fedevb94@hotmail.com
     on_failure: always 
     on_success: always
